### ISSUE TITLE
[Question] RequireJS support

### ISSUE THREAD

**Issue by ezecafre89** [Go-Promo/wjplayer#1]
Hey! First of all, thank you for the work done here! 
I was having issues integrating videojs with hls, and you guys saved my day.

I tried to include the library from requirejs, but then after taking a look at your source, I saw you guys are only supporting webpack. Is that right or am I doing something wrong?

For now, I had to add a script tag on my html file, but i will really appreciate any help to keep having a single request for all the js.

Thanks again.

**Comment by mkhazov** [comment]
Hey there, thanks for feedback!

I believe the library should be available as the amd module named `wjplayer`, because [we use](https://github.com/Go-Promo/wjplayer/blob/master/webpack.config.js#L28 ) `umd` [export format](https://webpack.github.io/docs/configuration.html#output-librarytarget).

If it's not, you can try to play with webpack configuration. Unfortunately, we do not use RequireJS, so I can not check it on my side.

**Comment by ezecafre89** [comment]
Well, I just tried again and it worked on the first try. I guess I was doing something wrong, not sure what, though.
Anyway, I can confirm that it works with requirejs!

Thanks for your time @mkhazov.
